# Generated by Django 4.2 on 2024-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to do'), ('in_process', 'in process'), ('finished', 'finished')], default='to_do', max_length=255),
        ),
    ]
